language: java

os:
  - linux
  
notifications:
  email: false

#######################################################################
cache:
  # Downloading octave takes a while, so let's cache apt
  apt: true
  
# Command to install dependencies
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y octave
  
#######################################################################
before_script:
  # Check for Octave installation
  - octave --version
  # Test that no exit conditions are used in the script
  - ! grep "exit" test_script.m
  # Add final exit condition
  - echo -e "\nexit(0)" >> test_script.m
  
#######################################################################
script:
  # Run Octave: if the script runs correctly, exit code should
  #             be 0, otherwise build fails   
  - octave -q --traditional --eval "test_script; exit(1);"
  
#######################################################################
# after_script:
#  - if [ $? -eq 1 ]; then
#        echo "OCTAVE -> Script FAILED";
#    else
#        echo "OCTAVE -> Script OK";
#    fi
  
