language: java

os:
  - linux
  
notifications:
  email: false

#######################################################################
cache:
  # Downloading octave takes a while, so let's cache apt
  apt: true
  
# Command to install dependencies
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y octave
  
#######################################################################
before_script:
  # Check what octave packages we have installed
  - octave --version
  - echo -e "\nexit(0)" >> test_script.m
  
#######################################################################
script:
  - octave -q --traditional --eval "test_script; exit(1);"
  - if [ $? -eq 1 ]; then
        echo "OCTAVE -> Script FAILED"
    else
        echo "OCTAVE -> Script OK"
    fi;
  
