language: java

os:
  - linux
  
notifications:
  email: false

#######################################################################
cache:
  # Downloading octave takes a while, so let's cache apt
  apt: true
  
# Command to install dependencies
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y octave
  
#######################################################################
before_script:
  # Check what octave packages we have installed
  - octave --version
  
#######################################################################
script:
  - octave -q --no-gui --traditional -eval "test_script.m; exit(1)"
  - if [ $? -eq 1 ]; then
        echo FAIL
    else
        echo OK
    fi;
  
